from typing import Protocol
from uuid import UUID

from app.domain.entities.answer import Answer
from app.domain.entities.audit_log import AuditLog
from app.domain.entities.citation import Citation
from app.domain.entities.document import Document
from app.domain.entities.document_chunk import DocumentChunk
from app.domain.entities.embedding import Embedding
from app.domain.entities.organization import Organization
from app.domain.entities.question import Question
from app.domain.entities.user import User


class UserRepositoryPort(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def exists_by_email(self, email: str) -> bool: ...

class OrganizationRepositoryPort(Protocol):
    async def get_by_id(self, organization_id: UUID) -> Organization | None: ...
    async def save(self, organization: Organization) -> Organization: ...

class DocumentRepositoryPort(Protocol):
    async def get_by_id(self, document_id: UUID) -> Document | None: ...
    async def list_by_owner(self, owner_id: UUID) -> list[Document]: ...
    async def list_by_organization(self, organization_id: UUID) -> list[Document]: ...
    async def save(self, document: Document) -> Document: ...
    async def delete(self, document_id: UUID) -> None: ...

class DocumentChunkRepositoryPort(Protocol):
    async def save_many(self, chunks: list[DocumentChunk]) -> list[DocumentChunk]: ...
    async def list_by_document_id(self, document_id: UUID) -> list[DocumentChunk]: ...

class EmbeddingRepositoryPort(Protocol):
    async def save(self, embedding: Embedding) -> Embedding: ...
    async def save_many(self, embeddings: list[Embedding]) -> list[Embedding]: ...

class QuestionRepositoryPort(Protocol):
    async def save(self, question: Question) -> Question: ...
    async def list_by_user_id(self, user_id: UUID) -> list[Question]: ...

class AnswerRepositoryPort(Protocol):
    async def save(self, answer: Answer) -> Answer: ...
    async def get_by_id(self, answer_id: UUID) -> Answer | None: ...
    async def get_by_question_id(self, question_id: UUID) -> Answer | None: ...

class CitationRepositoryPort(Protocol):
    async def save_many(self, citations: list[Citation]) -> list[Citation]: ...
    async def list_by_answer_id(self, answer_id: UUID) -> list[Citation]: ...

class AuditLogRepositoryPort(Protocol):
    async def save(self, audit_log: AuditLog) -> AuditLog: ...
    async def list_by_organization_id(self, organization_id: UUID) -> list[AuditLog]: ...
    async def list_all(self, limit: int = 100) -> list[AuditLog]: ...
