from typing import Protocol


class PasswordHasherPort(Protocol):
    def hash_password(self, plain_password: str) -> str: ...
    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...

class TokenProviderPort(Protocol):
    def create_access_token(self, subject: str, claims: dict[str, str] | None = None) -> str: ...
    def decode_access_token(self, token: str) -> dict[str, str]: ...
